---
base: &base
  url: https://esphome.io/
  webui: 'http://[HOST]:[PORT:6052]'
  startup: application
  boot: auto
  arch:
    - amd64
    - armv7
    - aarch64
  # Uses Hass.io API (auth)
  hassio_api: true
  auth_api: true
  hassio_role: default
  # Doesn't use HA API
  homeassistant_api: false
  # Host network mode for mDNS
  host_network: true
  # Ingress settings
  ingress: true
  ingress_port: 0
  panel_icon: 'mdi:chip'
  # Automatically add UART devices to addon
  auto_uart: true
  ports:
    '6052/tcp': null
  ports_description:
    '6052/tcp': "Web interface (Not required for Home Assistant Ingress)"
  map:
    - ssl:ro
    - config:rw
  schema:
    ssl: bool?
    certfile: str?
    keyfile: str?
    leave_front_door_open: bool?
    esphome_version: str?
    streamer_mode: bool?
    relative_url: str?
    status_use_ping: bool?
  base_image: esphome/esphome-hassio-base-{arch}:2.5.0

esphome-adafruit:
  <<: *base
  directory: esphome-adafruit
  name: ESPHome (Adafruit dev)
  version: 'dev'  # DEV
  slug: esphome-adafruit
  description: "Development Version! Manage and program ESP8266/ESP32 microcontrollers through YAML configuration files"
  url: https://next.esphome.io/
  stage: experimental
  options:
    esphome_version: dev

copy_files:
  icon.png:
  logo.png:
  README.md:
